<a href="https://colab.research.google.com/github/luisoliverph-web/TAREA-4/blob/main/EJERCICIOS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRACTICA CALIFICADA 01


1. Resolver con numpy los siguientes casos:
*   Crea un vector de números enteros del 1 al 20.
*   Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
*   Redimensiona una matriz de 4x4 a una matriz de 2x8.
*   Crea un array de 10 números equidistantes entre 0 y 1.
*   Concatena dos vectores vertical y horizontalmente. (concatenate)




In [17]:
import numpy as np

# Crea un vector de números enteros del 1 al 20.
vector_1_a_20 = np.arange(1, 21)
print("Vector de 1 a 20:")
print(vector_1_a_20)
print("-" * 30)

# Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
matriz_aleatoria_3x3 = np.random.rand(3, 3)
print("Matriz aleatoria 3x3:")
print(matriz_aleatoria_3x3)
print("-" * 30)

# Redimensiona una matriz de 4x4 a una matriz de 2x8.
matriz_4x4 = np.arange(16).reshape(4, 4)
matriz_redimensionada_2x8 = matriz_4x4.reshape(2, 8)
print("Matriz 4x4 original:")
print(matriz_4x4)
print("Matriz redimensionada 2x8:")
print(matriz_redimensionada_2x8)
print("-" * 30)

# Crea un array de 10 números equidistantes entre 0 y 1.
array_equidistante = np.linspace(0, 1, 10)
print("Array de 10 números equidistantes entre 0 y 1:")
print(array_equidistante)
print("-" * 30)

# Concatena dos vectores vertical y horizontalmente. (concatenate)
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
concatenacion_vertical = np.concatenate((vector1, vector2), axis=0)
concatenacion_horizontal = np.concatenate((vector1.reshape(-1, 1), vector2.reshape(-1, 1)), axis=1) # Reshape for horizontal

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Concatenación vertical:")
print(concatenacion_vertical)
print("Concatenación horizontal:")
print(concatenacion_horizontal)

Vector de 1 a 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
------------------------------
Matriz aleatoria 3x3:
[[0.3508695  0.39891574 0.21386468]
 [0.1769412  0.22759505 0.32912122]
 [0.2049122  0.12901904 0.11626672]]
------------------------------
Matriz 4x4 original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Matriz redimensionada 2x8:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
------------------------------
Array de 10 números equidistantes entre 0 y 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
------------------------------
Vector 1: [1 2 3]
Vector 2: [4 5 6]
Concatenación vertical:
[1 2 3 4 5 6]
Concatenación horizontal:
[[1 4]
 [2 5]
 [3 6]]


2. Resolver las siguientes operaciones:
*   Calcula la suma, resta, multiplicación y división de dos vectores.
*   Calcula la media, mediana y desviacion estandar de un vector.
*   Normaliza un vector dividiendo cada elemento por el valor máximo.
*   Encuentra el índice del valor máximo y mínimo en un vector.
*   Realiza una multiplicación matricial entre dos matrices 3x3.





In [18]:
import numpy as np

# Calcula la suma, resta, multiplicación y división de dos vectores.
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

suma_vectores = vector_a + vector_b
resta_vectores = vector_a - vector_b
multiplicacion_vectores = vector_a * vector_b
division_vectores = vector_a / vector_b

print("Vector a:", vector_a)
print("Vector b:", vector_b)
print("Suma de vectores:", suma_vectores)
print("Resta de vectores:", resta_vectores)
print("Multiplicación de vectores:", multiplicacion_vectores)
print("División de vectores:", division_vectores)
print("-" * 30)

# Calcula la media, mediana y desviacion estandar de un vector.
vector_stats = np.array([10, 20, 30, 40, 50])
media = np.mean(vector_stats)
mediana = np.median(vector_stats)
desviacion_estandar = np.std(vector_stats)

print("Vector para estadísticas:", vector_stats)
print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)
print("-" * 30)

# Normaliza un vector dividiendo cada elemento por el valor máximo.
vector_normalizar = np.array([10, 20, 5, 30, 15])
vector_normalizado = vector_normalizar / np.max(vector_normalizar)

print("Vector a normalizar:", vector_normalizar)
print("Vector normalizado:", vector_normalizado)
print("-" * 30)

# Encuentra el índice del valor máximo y mínimo en un vector.
vector_indices = np.array([10, 5, 20, 3, 15])
indice_max = np.argmax(vector_indices)
indice_min = np.argmin(vector_indices)

print("Vector para encontrar índices:", vector_indices)
print("Índice del valor máximo:", indice_max)
print("Índice del valor mínimo:", indice_min)
print("-" * 30)

# Realiza una multiplicación matricial entre dos matrices 3x3.
matriz_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
multiplicacion_matricial = np.dot(matriz_A, matriz_B)

print("Matriz A:")
print(matriz_A)
print("Matriz B:")
print(matriz_B)
print("Multiplicación matricial:")
print(multiplicacion_matricial)

Vector a: [1 2 3]
Vector b: [4 5 6]
Suma de vectores: [5 7 9]
Resta de vectores: [-3 -3 -3]
Multiplicación de vectores: [ 4 10 18]
División de vectores: [0.25 0.4  0.5 ]
------------------------------
Vector para estadísticas: [10 20 30 40 50]
Media: 30.0
Mediana: 30.0
Desviación estándar: 14.142135623730951
------------------------------
Vector a normalizar: [10 20  5 30 15]
Vector normalizado: [0.33333333 0.66666667 0.16666667 1.         0.5       ]
------------------------------
Vector para encontrar índices: [10  5 20  3 15]
Índice del valor máximo: 2
Índice del valor mínimo: 3
------------------------------
Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Multiplicación matricial:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


3. Resolver con numpy los siguientes casos:
*   Selecciona los elementos pares de un vector de números enteros.
*   Filtra los valores mayores que 5 en un vector
*   Filtra los valores iguales a cero
*   Filtra los valores negativos
*  Aplicar la media a los valores mayores de 50.



In [19]:
import numpy as np

# Selecciona los elementos pares de un vector de números enteros.
vector_enteros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
elementos_pares = vector_enteros[vector_enteros % 2 == 0]
print("Vector de números enteros:", vector_enteros)
print("Elementos pares:", elementos_pares)
print("-" * 30)

# Filtra los valores mayores que 5 en un vector
vector_filtro = np.array([2, 8, 1, 10, 4, 7, 3, 9, 6, 5])
valores_mayores_5 = vector_filtro[vector_filtro > 5]
print("Vector para filtrar:", vector_filtro)
print("Valores mayores que 5:", valores_mayores_5)
print("-" * 30)

# Filtra los valores iguales a cero
vector_cero = np.array([1, 0, 5, 0, 8, 2, 0, 4])
valores_iguales_cero = vector_cero[vector_cero == 0]
print("Vector con ceros:", vector_cero)
print("Valores iguales a cero:", valores_iguales_cero)
print("-" * 30)

# Filtra los valores negativos
vector_negativo = np.array([1, -2, 5, -8, 3, -1])
valores_negativos = vector_negativo[vector_negativo < 0]
print("Vector con números negativos:", vector_negativo)
print("Valores negativos:", valores_negativos)
print("-" * 30)

# Aplicar la media a los valores mayores de 50.
vector_media_filtro = np.array([10, 60, 30, 80, 40, 70, 20, 90, 50])
valores_mayores_50 = vector_media_filtro[vector_media_filtro > 50]
media_mayores_50 = np.mean(valores_mayores_50)
print("Vector para aplicar media con filtro:", vector_media_filtro)
print("Valores mayores que 50:", valores_mayores_50)
print("Media de valores mayores que 50:", media_mayores_50)

Vector de números enteros: [ 1  2  3  4  5  6  7  8  9 10]
Elementos pares: [ 2  4  6  8 10]
------------------------------
Vector para filtrar: [ 2  8  1 10  4  7  3  9  6  5]
Valores mayores que 5: [ 8 10  7  9  6]
------------------------------
Vector con ceros: [1 0 5 0 8 2 0 4]
Valores iguales a cero: [0 0 0]
------------------------------
Vector con números negativos: [ 1 -2  5 -8  3 -1]
Valores negativos: [-2 -8 -1]
------------------------------
Vector para aplicar media con filtro: [10 60 30 80 40 70 20 90 50]
Valores mayores que 50: [60 80 70 90]
Media de valores mayores que 50: 75.0


4. Resolver con numpy los siguientes casos:
*   Crea un vector de 10 elementos y reemplaza todos los valores mayores
que 5 con 0.
*   Combina dos vectores booleanos utilizando las operaciones & (AND) y I
(OR).
*   Cuenta la cantidad de valores en un vector que son múltiplos de 3.
*   Encuentra los índices de los elementos no nulos en un vector. (np.nonzero)
*   Comprueba si todos los elementos en un array son mayores que un valor
especifico digitado por el usuario.



5. Resolver con numpy los siguientes casos:
*   Calcula el cuadrado de cada elemento en un vector.
*   Utiliza la función exponencial para elevar todos los elementos de un vector
a la misma potencia.
*   Encuentra los valores máximos y mínimos en cada fila de una matriz.
*   Aplica la función sin a todos los elementos de un vector y almacena los
resultados en otro vector.
*   Realiza la transpuesta de una matriz 3x4.




In [20]:
import numpy as np

# Calcula el cuadrado de cada elemento en un vector.
vector_original = np.array([1, 2, 3, 4, 5])
vector_cuadrado = np.square(vector_original)
print("Vector original:", vector_original)
print("Cuadrado de cada elemento:", vector_cuadrado)
print("-" * 30)

# Utiliza la función exponencial para elevar todos los elementos de un vector a la misma potencia.
vector_base = np.array([1, 2, 3])
potencia = 3
vector_exponencial = np.power(vector_base, potencia)
print(f"Vector base: {vector_base}")
print(f"Potencia: {potencia}")
print(f"Resultado de elevar cada elemento a la potencia {potencia}: {vector_exponencial}")
print("-" * 30)

# Encuentra los valores máximos y mínimos en cada fila de una matriz.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
maximos_por_fila = np.max(matriz, axis=1)
minimos_por_fila = np.min(matriz, axis=1)
print("Matriz:")
print(matriz)
print("Valores máximos por fila:", maximos_por_fila)
print("Valores mínimos por fila:", minimos_por_fila)
print("-" * 30)

# Aplica la función sin a todos los elementos de un vector y almacena los resultados en otro vector.
vector_radianes = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
vector_sin = np.sin(vector_radianes)
print("Vector en radianes:", vector_radianes)
print("Resultado de aplicar la función sin:", vector_sin)
print("-" * 30)

# Realiza la transpuesta de una matriz 3x4.
matriz_3x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matriz_transpuesta = np.transpose(matriz_3x4)
print("Matriz 3x4 original:")
print(matriz_3x4)
print("Matriz transpuesta:")
print(matriz_transpuesta)

Vector original: [1 2 3 4 5]
Cuadrado de cada elemento: [ 1  4  9 16 25]
------------------------------
Vector base: [1 2 3]
Potencia: 3
Resultado de elevar cada elemento a la potencia 3: [ 1  8 27]
------------------------------
Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valores máximos por fila: [3 6 9]
Valores mínimos por fila: [1 4 7]
------------------------------
Vector en radianes: [0.         1.57079633 3.14159265 4.71238898 6.28318531]
Resultado de aplicar la función sin: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
------------------------------
Matriz 3x4 original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz transpuesta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


6. Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'.
Añade al menos 10 registros.
*   Del DataFrame creado, filtra a las personas que tienen más de 25 años.
*   A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellénala
con cualquier valor.
*   Encuentra el promedio de la edad en tu DataFrame.
*   Cuenta cuántas veces aparece cada ciudad en tu DataFrame.
*   Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para
cada ciudad. (groupby)
*   Ordena tu DataFrame por 'Edad', de manera ascendente y luego
descendente.



In [21]:
import pandas as pd

# Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'.
data = {'Nombre': ['Juan', 'Maria', 'Pedro', 'Ana', 'Luis', 'Sofia', 'Carlos', 'Elena', 'Diego', 'Lucia'],
        'Edad': [23, 31, 28, 25, 35, 29, 42, 22, 30, 27],
        'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Madrid', 'Barcelona', 'Valencia', 'Madrid', 'Sevilla', 'Barcelona']}
df = pd.DataFrame(data)

print("DataFrame original:")
print(df)
print("-" * 30)

# Del DataFrame creado, filtra a las personas que tienen más de 25 años.
df_mayores_25 = df[df['Edad'] > 25]
print("Personas mayores de 25 años:")
print(df_mayores_25)
print("-" * 30)

# A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellénala con cualquier valor.
df['Ingresos'] = [1200, 1500, 1300, 1100, 1800, 1400, 2000, 1000, 1600, 1350]
print("DataFrame con columna 'Ingresos':")
print(df)
print("-" * 30)

# Encuentra el promedio de la edad en tu DataFrame.
promedio_edad = df['Edad'].mean()
print(f"Promedio de edad en el DataFrame: {promedio_edad}")
print("-" * 30)

# Cuenta cuántas veces aparece cada ciudad en tu DataFrame.
conteo_ciudades = df['Ciudad'].value_counts()
print("Conteo de apariciones de cada ciudad:")
print(conteo_ciudades)
print("-" * 30)

# Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para cada ciudad. (groupby)
promedio_edad_por_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("Promedio de edad por ciudad:")
print(promedio_edad_por_ciudad)
print("-" * 30)

# Ordena tu DataFrame por 'Edad', de manera ascendente.
df_ordenado_asc = df.sort_values(by='Edad', ascending=True)
print("DataFrame ordenado por edad (ascendente):")
print(df_ordenado_asc)
print("-" * 30)

# Ordena tu DataFrame por 'Edad', de manera descendente.
df_ordenado_desc = df.sort_values(by='Edad', ascending=False)
print("DataFrame ordenado por edad (descendente):")
print(df_ordenado_desc)

DataFrame original:
   Nombre  Edad     Ciudad
0    Juan    23     Madrid
1   Maria    31  Barcelona
2   Pedro    28   Valencia
3     Ana    25    Sevilla
4    Luis    35     Madrid
5   Sofia    29  Barcelona
6  Carlos    42   Valencia
7   Elena    22     Madrid
8   Diego    30    Sevilla
9   Lucia    27  Barcelona
------------------------------
Personas mayores de 25 años:
   Nombre  Edad     Ciudad
1   Maria    31  Barcelona
2   Pedro    28   Valencia
4    Luis    35     Madrid
5   Sofia    29  Barcelona
6  Carlos    42   Valencia
8   Diego    30    Sevilla
9   Lucia    27  Barcelona
------------------------------
DataFrame con columna 'Ingresos':
   Nombre  Edad     Ciudad  Ingresos
0    Juan    23     Madrid      1200
1   Maria    31  Barcelona      1500
2   Pedro    28   Valencia      1300
3     Ana    25    Sevilla      1100
4    Luis    35     Madrid      1800
5   Sofia    29  Barcelona      1400
6  Carlos    42   Valencia      2000
7   Elena    22     Madrid      1000
8   Diego